### ISSUE TITLE
可以提供数据库参考下吗？

### ISSUE THREAD

**Issue by Realo7** [zhanyeye/dingtalk-springboot#37]

**Comment by zhanyeye** [comment]
+ 已回复邮件（数据表结构）
+ 另外这里用的 Spring JPA, 启动项目后会自动生成数据库

**Comment by zhanyeye** [comment]
已回复




詹泽晔
***@***.***

南京大学&nbsp;软件学院&nbsp;22届&nbsp;硕士生
电话：15776698528


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhanyeye/dingtalk-springboot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月12日(星期三) 晚上7:34
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zhanyeye/dingtalk-springboot] 可以提供数据库参考下吗？ (#37)

**Comment by Monkey0806** [comment]
同想要数据库参考下，感谢 @zhanyeye
